User.create!([
  {email: "1213.ghs@gmail.com", encrypted_password: "$2a$10$tXaej7C1el7sF4G2sA6ztOKN48rqi7XqAkfDlxnZmH6c0bhVn9ewS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2016-05-14 14:57:51", last_sign_in_at: "2016-05-14 14:05:18", current_sign_in_ip: "::1", last_sign_in_ip: "::1", auth_level: 99, money: 1007, username: "iqiq", gender: nil, age: nil, device: nil, OS: nil, time_spent: nil, spending: nil, motivation: nil, game_genre: nil, nation: nil, info: nil},
  {email: "wzhu37@uchicago.edu", encrypted_password: "$2a$10$8TJRK7nZ0h1dPbE82Kjx2eASLLDNbiVmSh4j7kkA0Ko0B4S6LvG1.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-05-14 14:59:32", last_sign_in_at: "2016-05-14 14:52:50", current_sign_in_ip: "::1", last_sign_in_ip: "::1", auth_level: 0, money: 50, username: "user1", gender: nil, age: nil, device: nil, OS: nil, time_spent: nil, spending: nil, motivation: nil, game_genre: nil, nation: nil, info: nil},
  {email: "1314.ghs@gmail.com", encrypted_password: "$2a$10$NGMPvbYdoPqUw1z6RDle0e17uVpDRXjuUOPYBuYf.mFpgpwQN42UK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-05-14 14:02:43", last_sign_in_at: "2016-05-14 14:02:43", current_sign_in_ip: "::1", last_sign_in_ip: "::1", auth_level: 0, money: 50, username: "user2", gender: nil, age: nil, device: nil, OS: nil, time_spent: nil, spending: nil, motivation: nil, game_genre: nil, nation: nil, info: nil},
  {email: "a@a.com", encrypted_password: "$2a$10$kWOcrEziFhjMkApXjCU8terwl7eVTN4Q32GO2d8MmBnvSTsl/uP42", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-05-14 16:49:36", last_sign_in_at: "2016-05-14 16:49:36", current_sign_in_ip: "::1", last_sign_in_ip: "::1", auth_level: 0, money: 0, username: "a", gender: nil, age: nil, device: nil, OS: nil, time_spent: nil, spending: nil, motivation: nil, game_genre: nil, nation: nil, info: nil},
  {email: "wanqizhu@wanqizhu.com", encrypted_password: "$2a$10$cjc1/wNWuMr1VkTIw06dtON6eX.FjOy66evDpwfjr9XNXEwWH0G5C", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-05-14 17:14:59", last_sign_in_at: "2016-05-14 16:50:06", current_sign_in_ip: "::1", last_sign_in_ip: "::1", auth_level: 0, money: 50, username: "wanqi", gender: nil, age: nil, device: nil, OS: nil, time_spent: nil, spending: nil, motivation: nil, game_genre: nil, nation: nil, info: nil},
  {email: "ray.liu@chicagobooth.edu", encrypted_password: "$2a$10$Kbx5YfD15ONniKSHNU8rauAcM43TfjT1/PvG7OBoO0x/IJ7xfychW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-05-15 01:04:02", last_sign_in_at: "2016-05-15 01:04:02", current_sign_in_ip: "::1", last_sign_in_ip: "::1", auth_level: 99, money: 85, username: "ray", gender: nil, age: nil, device: nil, OS: nil, time_spent: nil, spending: nil, motivation: nil, game_genre: nil, nation: nil, info: nil},
  {email: "genius.754@outlook.com", encrypted_password: "$2a$10$tj5tDb9wrAcYcs6M2QoZF.qji7AkL/Nuh2U/8okVIPouhVp/9caxy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-05-16 01:25:17", last_sign_in_at: "2016-05-16 01:25:17", current_sign_in_ip: "::1", last_sign_in_ip: "::1", auth_level: 0, money: 135, username: "survey002_test", gender: nil, age: nil, device: nil, OS: nil, time_spent: nil, spending: nil, motivation: nil, game_genre: nil, nation: nil, info: nil}
])
Link.create!([
  {title: "Rewards!", url: "http://eepurl.com/bNhxoj", content: "We are rolling out our preliminary rewards structure. Start earning WillowCoins today!", user_id: 1, cached_votes_total: 0, cached_votes_score: 0, cached_votes_up: 0, cached_votes_down: 0, cached_weighted_score: 0, cached_weighted_total: 0, cached_weighted_average: 0.0},
  {title: "First Survey!", url: "http://eepurl.com/b0OW9b", content: "Start playing League of Angels - Fire Raiders today, and come back and tell us what you think!", user_id: 1, cached_votes_total: 0, cached_votes_score: 0, cached_votes_up: 0, cached_votes_down: 0, cached_weighted_score: 0, cached_weighted_total: 0, cached_weighted_average: 0.0}
])
